###
GET http://localhost:5000/grocery
Content-Type: application/json
###

###
POST http://localhost:5000/grocery/add
Content-Type: application/json

{ "item":  "cupcake" }
###

###
PUT http://localhost:5000/grocery/update
Content-Type: application/json

{ "prev": "cupcake", "next": "just cake" }
###

###
DELETE http://localhost:5000/grocery/delete/rice
Content-Type: application/json
###